version: '3'
services:
    reverse-proxy:
        image: nginx:latest
        volumes:
            - ./client/public:/usr/share/nginx/html
            - ./config/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:80"
        restart: always
        depends_on:
            - socket-server
    socket-server:
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
    composer:
        image: "composer"
        volumes:
            - "./server:/app"
        command: install