version: "3"
services:
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - socket-server
      - php
      - db
      - memcached
  socket-server: # 8080
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
      - memcached
    env_file:
      - .env
  memcached: # port 11211
    restart: always
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
  php-composer:
    image: "composer"
    volumes:
      - "./client:/app"
    command: install
  php: # port 9000
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - db
      - memcached
  composer-socket-server:
    image: "composer"
    volumes:
      - "./server:/app"
    command: install
  db: # port 3306
    container_name: db
    image: mysql:latest
    restart: always
    volumes:
      - ./server/src/Db/script/db.sql:/docker-entrypoint-initdb.d/db.sql
    env_file:
      - .env
